//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmstaJanBonga.Admin.Content.Secure.Help {
    
    
    public partial class Help {
        
        /// <summary>
        /// LegendaWidget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AmstaJanBonga.Admin.Content.Controls.LegendaWidget.LegendaWidget LegendaWidget;
    }
}
